### PR TITLE
Use bundle mode for components instead of ngl

### LINKED ISSUE #7: Bundle Mode in ESM CDN and importmaps
ESM CDN has a Bundle Mode to put all dependencies into a single JS file, see [doc](https://esm.sh/#docs). We use the `?bundle` in [example.local.html](https://github.com/i-VRESSE/haddock3-analysis-components/blob/1d5e82fe24b3a9f9134c71eb541b1597277ce504/example.local.html#L15) when importing ngl in order to fix the error `Uncaught (in promise) TypeError: tp.scale is not a function`. When using bundle mode, `ngl.bundle.mjs` file is created under esm.sh, see 
image

However, this solution does not work for [example.html](https://github.com/i-VRESSE/haddock3-analysis-components/blob/1d5e82fe24b3a9f9134c71eb541b1597277ce504/example.html#L18) and `ngl.bundle.mjs` file is **NOT** created. Instead when `?bundle` is added to haddock3-analysis-components i.e. `"https://esm.sh/@i-vresse/haddock3-analysis-components?bundle"`, the example works.

### PR DESCRIPTION
**Pull request by SarahAlidoost**
closes #7

### CODE REVIEW

**Comment by SarahAlidoost** [comment]
@sverhoeven Can you please have a look at #7, I amnot sure the reason why adding `?bundle` to ngl does not work.

File: example.html [hunk 1]
```diff
@@ -15,8 +15,8 @@
         "imports": {
           "react": "https://esm.sh/react",
           "react-dom": "https://esm.sh/react-dom",
-          "ngl": "https://esm.sh/ngl?bundle",
-          "@i-vresse/haddock3-analysis-components": "https://esm.sh/@i-vresse/haddock3-analysis-components"
+          "ngl": "https://esm.sh/ngl",
```
Comment (sverhoeven) [inline example.html:18]: Line is no longer needed as it imported by the line below

```suggestion
```

**Review by sverhoeven — APPROVED** [review]
example.html works with the 0.3.0 version from npm. Thanks making the release.

Without this fix the h3ac was including ngl without `?bundle`. 

```js
/* esm.sh - @i-vresse/haddock3-analysis-components@0.3.0 */
import "/stable/react@18.2.0/es2022/react.mjs";
import "/v132/ngl@2.1.1/es2022/ngl.mjs";
export * from "/v132/@i-vresse/haddock3-analysis-components@0.3.0/es2022/haddock3-analysis-components.mjs";
```

Causing the error why we added ?bundle to ngl.

So this is indeed the right fix.
